export interface PermissionarioModelo {
  idPermissionario: number
  numeroPermissao: string
  nomePermissionario: string
  cpfPermissionario: string
  rgPermissionario: string
  orgaoEmissor: string
  filiacaoMae: string
  filiacaoPai: string
  sexo: string
  estadoCivil: string
  dataNascimento: string
  ufPermissionario: string
  cidadePermissionario: string
  bairroPermissionario: string
  enderecoPermissionario: string
  cep: string
  celularPermissionario: string
  emailPermissionario: string
  cnhPermissionario: string
  categoriaCnhPermissionario: string
  dataValidadeCnh: string
  numeroQuitacaoMilitar: string
  numeroQuitacaoEleitoral: string
  numeroInscricaoInss: string
  numeroCertificadoCondutor: string
  dataValidadeCertificadoCondutor: string
  dataCriacao: string
  usuario: string
  status: string
  aplicativoAlternativo: string
  observacao: string
}
