export interface DefensorModelo {
  idDefensor: number
  numeroPermissao: string
  nomeDefensor: string
  cpfDefensor: string
  rgDefensor: string
  orgaoEmissor: string
  filiacaoMae: string
  filiacaoPai: string
  sexo: string
  estadoCivil: string
  dataNascimento: string
  ufDefensor: string
  cidadeDefensor: string
  bairroDefensor: string
  enderecoDefensor: string
  cep: string
  celularDefensor: string
  emailDefensor: string
  cnhDefensor: string
  categoriaCnhDefensor: string
  dataValidadeCnh: string
  numeroQuitacaoMilitar: string
  numeroQuitacaoEleitoral: string
  numeroInscricaoInss: string
  numeroCertificadoCondutor: string
  dataValidadeCertificadoCondutor: string
  dataCriacao: string
  usuario: string
  status: string
}
