export interface VeiculoModelo {
  idVeiculo: number
  idPermissionario: string
  idPontoTaxi: string
  numeroPermissao: string
  placa: string
  renavam: string
  chassi: string
  anoFabricacao: string
  marca: string
  modelo: string
  anoModelo: string
  cor: string
  combustivel: string
  capacidade: string
  quilometragem: string
  numeroTaximetro: string
  anoRenovacao: string
  dataVistoria: string
  dataRetorno: string
  statusVistoria: string
  situacaoVeiculo: string
  numeroCrlv: string
  anoCrlv: string
  certificadoAfericao: string
  tipoVeiculo: string
  observacao: string
  dataCriacao: string
  usuario: string
  status: string
}
